{
 "title": "Telegram bot logs",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "filter" }
  ]
 },
 "panels": [
  {
   "title": "Logs levels",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(level) (count_over_time({filename=\"/logs/bot.log\"} |= `$filter` | logfmt | level =~ `.+` [$__auto]))"
    }
   ]
  },
  {
   "title": "Logger data",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 5, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(logger) (count_over_time({filename=\"/logs/bot.log\"} |= `$filter` | logfmt | logger =~ `.+` [$__auto]))"
    }
   ]
  },
  {
   "title": "Number of all logs",
   "type": "stat",
   "gridPos": { "h": 11, "w": 7, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({filename=\"/logs/bot.log\"} |= `$filter` | logfmt[15d]))"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "{filename=\"/logs/bot.log\"} |= `$filter` | logfmt"
    }
   ]
  }
 ]
}