
replicaCount: 1

image:
  repository: eugenek6/germes_bot
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

secret:
  name: app-secrets

service:
  ports:
    - port: 5000
      targetPort: healthcheck
  type: ClusterIP

ingress:
  annotations:
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: germes-manager-auth-secret
    nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required'
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  ingressClassName: nginx
  host: germes-bot-manager.online
  service:
    name: user-manager
    port:
      number: 5000
  tls:
    hosts: germes-bot-manager.online
    secretName: user-manager-germes-tls