apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: germes-the-bot
spec:
    selector:
        app: postgres
    ports:
        - protocol: TCP
          port: 5432
          targetPort: 5432