positions:
  filename: /logs/positions.yaml

clients:
  - url: http://loki-local:3100/loki/api/v1/push

scrape_configs:
  - job_name: telegram-bot
    static_configs:
      - targets:
          - localhost
        labels:
          __path__: /logs/bot.log
  - job_name: user-manager
    static_configs:
      - targets:
          - localhost
        labels:
          __path__: /logs/user-manager.log