{
 "title": "Kubernetes logs",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "filter" },
   { "name": "Data_source", "label": "Data_source", "query": "loki" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {}
   },
   {
    "name": "app",
    "query": {}
   },
   {
    "name": "container",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Logs levels",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(level) (count_over_time({namespace=\"$namespace\", app=\"$app\", container=\"$container\"} |= `$filter` | logfmt | level =~ `.+` [$__auto]))"
    }
   ]
  },
  {
   "title": "Number of all logs",
   "type": "stat",
   "gridPos": { "h": 11, "w": 7, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", app=\"$app\", container=\"$container\"}|= `$filter` | logfmt[$__auto]))"
    }
   ]
  },
  {
   "title": "Logs debug",
   "type": "table",
   "gridPos": { "h": 11, "w": 21, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "{namespace=\"$namespace\", app=\"$app\", container=\"$container\"} | logfmt | msg =~ `.*$filter.*` "
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 21, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "{namespace=\"$namespace\", app=\"$app\", container=\"$container\"} | logfmt | msg =~ `.*$filter.*` "
    }
   ]
  }
 ]
}