grafana:
  enabled: true
  persistence:
    type: pvc
    enabled: true
    storageClassName: microk8s-hostpath
    accessModes:
      - ReadWriteOnce
    size: 1Gi

promtail:
  config:
    positions:
      filename: /run/promtail/positions_germes.yaml

loki:
  persistence:
    enabled: true
    accessModes:
      - ReadWriteOnce
    size: 5Gi
    storageClassName: microk8s-hostpath