name: Telegram Bot Kubernetes

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    paths:
      - 'liquibase/**'
      - 'Telegram_bot/**'
      - 'helm-charts/telegram-bot/**'

jobs:
  test_build_push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Populate .env file
      run: |
        touch .env
        echo "${{ secrets.FULL_ENV }}" >> .env

    - name: Run unit tests
      run: |
        docker compose run --build --rm telegram-bot python test_bot.py

    - name: Set up Python 3.9 for pylint
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'

    - name: Install pylint
      run: |
        python -m pip install --upgrade pip
        pip install pylint

    - name: Install dependencies for pylint
      run: |
        pip install -r requirements.txt
      working-directory: ./Telegram_bot

    - name: Analysing the code with pylint
      run: |
        pylint ./Telegram_bot

    - name: Set commit hash
      run: echo "COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    - name: Build bot docker image
      run: docker build . --tag eugenek6/germes_bot:telegram_bot_${{ env.COMMIT_HASH }}
      working-directory: ./Telegram_bot

    - name: Build liquibase docker image
      run: docker build . --tag eugenek6/germes_bot:liquibase_${{ env.COMMIT_HASH }}
      working-directory: ./liquibase

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push the telegram docker image
      run: docker push eugenek6/germes_bot:telegram_bot_${{ env.COMMIT_HASH }}

    - name: Push the liquibase docker image
      run: docker push eugenek6/germes_bot:liquibase_${{ env.COMMIT_HASH }}

    - uses: azure/setup-helm@v4.2.0

    - name: Configure kube config
      run: |
        echo "${{ secrets.KUBE_CONFIG }}" > kubeconfig
        mkdir -p ~/.kube
        mv kubeconfig ~/.kube/config
        chmod 600 ~/.kube/config

    - name: helm upgrade --install
      run: |
        helm --namespace germes-the-bot upgrade --install telegram-bot --set image.tag=${{ env.COMMIT_HASH }} --wait ./telegram-bot
      working-directory: ./helm-charts
